import Head from 'next/head'
import About from '../components/About'
import ContactMe from '../components/ContactMe'
import Diploma from '../components/Diploma'
import Gallery from '../components/Gallery'
import Header from '../components/Header'
import Hero from '../components/Hero'
import Skills from '../components/Skills'
import WorkExperience from '../components/WorkExperience'




export default function Home() {
  return (
    <div className='bg-[rgb(36,36,36)] text-white h-screen snap-y snap-mandatory overflow-scroll z-0
    scrollbar scrollbar-track-gray-400/20 scrollbar-thumb-[#F7AB0A]/80'>
      <Head>
        <title>Mikael portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      {/* Header */}
      <Header />

      {/* Hero */}
      <section id='hero' className='snap-center'>
         <Hero />
      </section>
      {/* A propos */}
      <section id='about' className='snap-center'>
        <About />
      </section>

      {/* Expérience */}
      <section id='experience' className='snap-center'>
        <WorkExperience />
      </section>

      {/* Skill */}
      <section id='skills' className='snap-start'>
        <Skills />
      </section>
      {/* Diplome */} 
      <section id='diploma' className='snap-start'>
        <Diploma />
      </section>

      {/* Galerie */}
      <section id='gallery' className='snap-start'>
        <Gallery />
      </section>

      {/* Me contacter */}
      <section id='contact' className='snap-start'>
        <ContactMe />
      </section>

    </div>
  )
}
